const ROUTES = {
    cleaner_onboarding: 'Onboarding',
    cleaner_dashboard: 'Home',
    cleaner_home_tab:'Home Tab',
    cleaner_home_tab_mock:'Home Tab Mock',
    cleaner_home_drawer: 'Home Drawer',
    cleaner_profile: 'Profile',
    cleaner_verification: 'User Identity Verification',
    cleaner_jobs: 'Jobs',
    cleaner_job_application_details: 'Application Details',
    cleaner_messages: 'Messages',
    cleaner_conversations: 'Conversations',
    cleaner_feedbacks: 'Freedbacks',
    cleaner_more:'More',
    cleaner_personal_profile_drawer: 'Personal Profile',
    cleaner_support:'Support',
    cleaner_settings:'Settings',
    cleaner_schedules:'My Schedules',
    cleaner_schedule_details:'Schedule Details',
    cleaner_schedule_details_view:'Schedule Info',
    cleaner_schedule_review:'Review & Confirm Schedule',
    cleaner_job_details:'Job Details',
    cleaner_attach_task_photos:'Attach Task Photos',
    cleaner_profile_info:'Profile Info',
    cleaner_profile_Pay:'Profile & Pay',
    cleaner_all_requests:'All Requests',
    cleaner_clock_in:'Clock-In',
    cleaner_application:'Applications',
    cleaner_payment:'Payment',
    cleaner_payment_onboarding:'Payment',
    cleaner_id_verification:'ID Verification',
    cleaner_tax_information:'Update Tax Information',
    cleaner_change_password:'Change Password',
    cleaner_change_language:'Change Language',
    cleaner_payment_history:'Payment History',

    host_home_tab: "Home",
    host_home_drawer:"Dashboard Host",
    host_profile: "Profile",
    host_change_password: 'Change Password',
    host_change_language:'Change Language',
    host_schedule_details: "Schedule Details",
    host_application: "My  Application",
    host_dashboard: "Home",
    host_request_list: "Requests",
    host_bookings: "Bookings",
    host_messages: 'Messages',
    host_conversations: 'Conversations',
    host_feedbacks: 'Freedbacks',
    host_apartments: "Apartments",
    host_add_apt: "Add Apartment",
    host_edit_apt: "Edit Apartment",
    host_apt_dashboard: "Apartment Dashboard",
    host_new_booking: "Recommended Cleanser",
    host_recommended_cleaners: "Create New Booking",
    host_my_apartment: "My Apartments",
    host_find_cleaners: "Find Cleaners",
    host_more:'More',
    host_confirm:'Confirm Request',
    host_task_progress: "Task Progress",
    host_payment_history: "Payment History",
    host_checkout: "Make Payment",
    host_single_checkout:" Make Payment",
    host_schedule_approval:"Approve Schedule",


    getting_started: "Getting Started",
    onboarding: "On Boarding",
    signin_mock: "Sign In Mock",
    signin: "Sign In",
    signup: "Sign Up",
    forgot_password:"Forgot Password",
    reset_password:"Reset Password",
    signup_mock: "Sign Up Mock",
    chat_conversation:"Chat Conversation",
    cleaner_chat_conversation:"CleanChat Conversation"



  };

  export default ROUTES